import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import RootProviders from "@/app/providers/root-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProviders>
          <Navbar />
          {children}
        </RootProviders>
      </body>
    </html>
  );
}

// import "./globals.css";
// import { Inter } from "next/font/google";
// import RootProviders from "@/app/providers/root-providers";
// import Navbar from "@/components/Navbar/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <RootProviders>
//           <Navbar />
//           {children}
//         </RootProviders>
//       </body>
//     </html>
//   );
// }
